### ISSUE TITLE
Hosting on Heroku

### ISSUE THREAD

**Issue by kchu93** [kevinchu676/visual-movement#1]
- [x] Hosting

**Comment by kchu93** [comment]
https://visualmovement.herokuapp.com/#/

**Comment by evhumphrey** [comment]
Reopened because when you turn it in, you need to make sure it's production ready on Heroku (so this issue will be a reminder)

We have a reading on this, but includes: 
- [ ] Remove all console.logs
- [ ] Remove everything from window
- [ ] Remove Redux logger

https://github.com/appacademy/curriculum/blob/master/full-stack-project/resources/helpful_tools/production-ready.md
